### ISSUE TITLE
Get Folders doesn't seem to match the API

### ISSUE THREAD

**Issue by saimsiddiqui** [ComfortablyCoding/clickup.js#19]
In src/routes/Spaces.js the GetFolders end point doesn't match the API spec. It seems to be missing the ending.

This is the expected api call (notice the ending `folder?archived=false`):
https://api.clickup.com/api/v2/space/space_id/folder?archived=false

This is what is in the code:
https://github.com/ComfortablyCoding/clickup.js/blob/afe927b0cc0cbb972f7af172a8b13cb69ba10aa0/src/routes/Spaces.js#L67

**Comment by ComfortablyCoding** [comment]
Thank you for pointing that out. It has now been fixed by #20
