### ISSUE TITLE
PUT requests fail with error

### ISSUE THREAD

**Issue by adamj88** [ComfortablyCoding/clickup.js#2]
When trying to do a PUT request, e.g: `clickup.tasks.update()` the following error occurs:

```
The `body` option must be a stream.Readable, string or Buffer
```

The problem looks to relate to this line: https://github.com/ComfortablyCoding/clickup.js/blob/master/src/index.js#L117

Which should pass through the `options`:  

```diff
- return this._service.put(endpoint, { searchParams, body });
+ return this._service.put(endpoint, options);
```

**Comment by ComfortablyCoding** [comment]
Agreed, thank you for pointing it out.
