### ISSUE TITLE
Fetch time entries by date range

### ISSUE THREAD

**Issue by johnsBeharry** [ComfortablyCoding/clickup.js#30]
Hey awesome work thanks for making this. I was just assessing the library docs and was wondering there was an easy way to get all time log entries from an entire space/list for a certain range.

**Comment by ComfortablyCoding** [comment]
Hello @johnsBeharry,

You can use the [Get time entries within a date range](https://jsapi.apiary.io/apis/clickup20/reference/0/time-tracking-20/get-time-entries-within-a-date-range.html) endpoint. It supports a variety of parameters including start_date, end_date, space_id and list_id which I believe is relevant to your use case. 

If you were using this library to do so, it would be via the following function
```js
clickup.teams.getTimeEntries(teamId,params);
```
