### ISSUE TITLE
Feature Request: Support API in EU (European Union)

### ISSUE THREAD

**Issue by ngraf** [ComfortablyCoding/clickup.js#36]
*Current state* 
I cannot use the library for ClickUp workspaces hosted in European Union, since the American API endpoint is hardcoded in 		`prefixUrl: 'https://api.clickup-eu.com/api/v2',` in `createRequestInstance.js`

*Desired state* 
The user of the library is able to override the default US `prefixUrl` in some way in order to use the library also in different regions like EU.

*Info*
I tested and manually changed `prefixUrl` to `'https://api.clickup-eu.com/api/v2'` in local code.
-> it works. All I need now is a permanent solution within the library.

**Comment by ComfortablyCoding** [comment]
All request options including the `prefixUrl` are currently overrideable via the `requestOptions` param of clickup instance.

In your case it would be 
```js
const clickup = new Clickup(token, {
  prefixUrl: "https://api.clickup-eu.com/api/v2",
});
```

**Comment by ngraf** [comment]
ah, I see. Cool 👍🏻
